### ISSUE TITLE
Exception loading 'v4.vcf'

### ISSUE THREAD

**Issue by jbrockerville** [bolorundurowb/vCardLib#46]
Ran with `vCardLib/vCardLib.Tests/v4.vcf`
```
   at vCardLib.Deserializers.v4Deserializer.ParseAddresses(String[] contactDetails)
   at vCardLib.Deserializers.Deserializer.Deserialize(String[] contactDetails)
   at vCardLib.Deserializers.Deserializer.GetCardFromContact(String[] contact)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at vCardLib.Deserializers.Deserializer.CreateCardsFromContacts(IEnumerable`1 contacts)
   at vCardLib.Deserializers.Deserializer.FromFile(String filePath)
   at source.cs:line 39
```

**Comment by bolorundurowb** [comment]
@jbrockerville unfortunately, v4 vcard files are not supported by the library. There hasn't been a lot of community request for  support. If you can, you can contribute support

**Comment by bolorundurowb** [comment]
@jbrockerville with the release of v5.0.0 vcard v4 support has been added
